
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker
spec:
  template:
    spec:
      containers:
        - name: kafka-broker
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: dev-kafka-cluster
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: dev-zookeeper:2181