matrix:
  include:
    - language: python
      env:
        - PIPENV_VERBOSITY=-1
      python:
        - "3.8"
      install:
        - "pip install pipenv"
        - "cd log-scraper && pipenv install --dev"
      script:
        - "python -m unittest"
