matrix:
  include:
    - language: python
      python:
        - "3.8"
      install:
        - pip install pipenv
        - pipenv install --dev
      script:
        - "python -m unittest discover log-scraper"

    - language: python
      python:
        - "3.6"
        - "3.7"
        - "3.8"
      script:
        - "python -m unittest discover ."
