matrix:
  include:
    - language: python
      env:
        - PIPENV_VERBOSITY=-1
      python:
        - "3.8"
      before_install:
        - sudo apt-get install libgnutls28-dev
      install:
        - pip install pipenv
        - cd log-scraper && pipenv install --dev
      script:
        - python -m unittest
