matrix:
  include:
    - language: python
      python:
        - "3.8"
      install:
        - "pip install pipenv"
        - "cd log-scraper && pipenv install --dev"
      script:
        - "cd log-scraper && pipenv run python -m unittest"
