version: '3'
services:
  web:
    build: .
    ports:
     - "9000:80"
  log-scraper:
    build:
      context: log-scraper
  geocoder:
    build:
      context: geocoder
  mongodb:
    image: "mongo:3.0"
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db