version: '2'
services:
  web:
    build: .
    ports:
     - "9000:80"
    links:
      - "mongodb"
    depends_on:
      - "mongodb"
  mongodb:
    image: "mongo:3.0"
    container_name: "mongodb"
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db