apiVersion:  batch/v1beta1
kind: CronJob
metadata:
  name: crime-map-geocoder
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: geocoder
            image: g1ymoore/crime-map:geocoder
            volumeMounts:
              - name: google-maps
                mountPath: "/usr/share/crime-map/secrets"
          restartPolicy: OnFailure
          volumes:
            - name: google-maps
              secret:
                secretName: google-maps
                items:
                  - key: api-key
                    path: google-maps-key
                    mode: 511
