apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: log-scraper
  namespace: crime-map
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: log-scraper
            image: g1ymoore/crime-map:log-scraper
            resources:
              requests:
                memory: "64Mi"
                cpu: "125m"
              limits:
                memory: "128Mi"
                cpu: "250"
            volumeMounts:
              - mountPath: "/usr/share/crime-map/secrets"
                name: google-maps
          restartPolicy: OnFailure
          volumes:
            - name: google-maps
              secret:
                secretName: google-maps
                items:
                  - key: api-key
                    path: google-maps-key
                    mode: 511
